### PR TITLE
fix: Automation Script Modification

### LINKED ISSUE #210: Automation Script Modification
**What happened**: The automation script is throwing an error when used.

**What you expected to happen**: It runs correctly.

**How to reproduce it (as minimally and precisely as possible)**: Execute directly.

**Anything else we need to know?**:

**Environment**:
- Kosmos version: v0.1.7
- Others:

### PR DESCRIPTION
**Pull request by lvtaococo**
#### What type of PR is this?
/kind bug

#### What does this PR do?

Automation Script Modification
#### Which issue(s) does this PR fix?

Fixes #210 
#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by lvtaococo** [comment]
@hanweisen @duanmeng @wuyingjun-lucky

**Comment by duanmeng** [comment]
> @hanweisen @duanmeng @wuyingjun-lucky

@lvtaococo Why at me?

**Comment by lvtaococo** [comment]
@duanmeng Sorry, I thought you were my colleague. Your real name is the same as my colleague's.

**Comment by duanmeng** [comment]
> @duanmeng Sorry, I thought you were my colleague. Your real name is the same as my colleague's.

Small world hahaha

**Pull request merged**
