### PR TITLE
feature: precheck ns and api-resources in sync leaf

### PR DESCRIPTION
**Pull request by rxy0210**
#### What type of PR is this?
/kind feature

#### What does this PR do?

precheck ns and api-resources in sync leaf
#### Which issue(s) does this PR fix?

Fixes #
#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rxy0210** [comment]
image
e2e failed, because i add new parameters in clustertree
pkg/kosmosctl/manifest/manifest_deployments.go

image

cmd/clustertree/cluster-manager/app/options/options.go

image

**Comment by duanmengkk** [comment]
Please solve the problem with github ci first

**Comment by rxy0210** [comment]
> Please solve the problem with github ci first

fixed

**Pull request merged**
