### PR TITLE
fix: use master config to init resourcemanager for adapter

### PR DESCRIPTION
**Pull request by OrangeBao**
#### What type of PR is this?
fix

#### What does this PR do?

use master config to init resourcemanager for adapter

#### Which issue(s) does this PR fix?

Fixes #
#### Screenshots (if applicable):

```release-note

```

#### Additional Comments:

```release-note

```

### CODE REVIEW

**Review by rxy0210 — COMMENTED** [review]
/lgtm

**Review by wangyizhi1 — APPROVED** [review]

**Pull request merged**
