### PR TITLE
feat: support find cilium cluster ip cidr

### PR DESCRIPTION
**Pull request by hanweisen**
#### What type of PR is this?
support find cilium cluster ip cidr

/kind feature
#### What does this PR do?

write cilium managed cluster ip in cluster.kosmos.io

#### Which issue(s) does this PR fix?

Fixes part of #311
#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by wuyingjun-lucky** [comment]
@hanweisen  It is a new feature，I think we can make an issue

**Comment by hanweisen** [comment]
@yuleichun-striving  cni config `cilium `

**Comment by hanweisen** [comment]
> @hanweisen It is a new feature，I think we can make an issue

I add a issue, fef: #311

**Comment by wuyingjun-lucky** [comment]
@hanweisen  can we add e2e for this situation

**Comment by hanweisen** [comment]
This would require creating a new cluster and deploying Cilium on it, which would extend the execution time of end-to-end (e2e) tests.

**Comment by wuyingjun-lucky** [comment]
> This would require creating a new cluster and deploying Cilium on it, which would extend the execution time of end-to-end (e2e) tests.

It does not matter，I want add calico、flannel and cilium test.

**Pull request merged**
