### PR TITLE
fix: null pointer exception when creating routes

### PR DESCRIPTION
**Pull request by wangyizhi1**
#### What type of PR is this?

/kind bug

#### What does this PR do?

fix null pointer exception when creating routes

#### Which issue(s) does this PR fix?

Fixes #
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by wuyingjun-lucky** [comment]
@wangyizhi1 please add issue link

**Comment by wangyizhi1** [comment]
fix: #219

**Pull request merged**
