### PR TITLE
fix: fix the kosmos deploy yaml error

### PR DESCRIPTION
**Pull request by duanmengkk**
#### What type of PR is this?
- **fix:** fix bug

#### Which issue(s) does this PR fix?

Fixes #
#### Screenshots (if applicable):

```release-note

```

#### Additional Comments:

```release-note

```

### CODE REVIEW

**Comment by duanmengkk** [comment]
and we should cherry pick it to main @wuyingjun-lucky

**Comment by wuyingjun-lucky** [comment]
> and we should cherry pick it to main @wuyingjun-lucky

OK I will find how to cherry pick

**Pull request merged**
